### ISSUE TITLE
stuck when uploading

### ISSUE THREAD

**Issue by sakarimov** [maximmaxim345/sheepit-plugin#4]
![image](https://user-images.githubusercontent.com/5676876/151897871-944c828c-8b73-4aff-8893-1e858ad1a9e0.png)

i found that error when trying to upload my project

btw, thank u for very quick reply on latest issue

**Comment by maximmaxim345** [comment]
Strange, the "Preparing Scene" step packs all textures and compresses the blend file so it could take a while.
Does this happen in all Projects?

**Comment by sakarimov** [comment]
i did'nt try another project yet, i'll try it, and report the result soon

**Comment by sakarimov** [comment]
i've tried another file, and it still stuck in 5%, still no continue

**Comment by maximmaxim345** [comment]
Ok, just tried the plugin on my Linux machine.
Instead of compressing the blend file it just started a new blender instance (only on linux).
The newest release should work now.

**Comment by sakarimov** [comment]
thank u for your fast respond @maximmaxim345, i still have problem when i want to upload, this is with newest version
![image](https://user-images.githubusercontent.com/5676876/152142756-51fad997-5e92-4b2b-9166-d2235a2224e0.png)

thank you very much for your help

**Comment by maximmaxim345** [comment]
Ok, thats strange. Could you Install [this](https://github.com/maximmaxim345/sheepit-plugin/files/7986772/sheepit-plugin.zip) version of the plugin and send me the log.

**Comment by sakarimov** [comment]
thank you very much @maximmaxim345, the problem is solved, the add-on runs smoothly, 
![image](https://user-images.githubusercontent.com/5676876/152232497-39016891-50d5-471b-924b-be22b684e9c1.png)

i guess, about the last error message, it's because of unfinished job (whatever it's named), before installing v0.2.5 i ran v0.2.4, because of an error i forcely closed blender

btw thank u very much :)

**Comment by maximmaxim345** [comment]
That explanes the strange Error.
I will now close this issue.

You're welcome.
